apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:14.21-alpine3.23
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "captainslog"
        - name: POSTGRES_USER
          value: "captainslog"
        - name: POSTGRES_PASSWORD
          value: "Pg#123"

---

apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  selector:
    app: postgresql
  ports:
  - port: 5432
    targetPort: 5432

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: captainslog
spec:
  selector:
    matchLabels:
      app: captainslog
  template:
    metadata:
      labels:
        app: captainslog
    spec:
      containers:
      - name: captainslog
        image: rukasu/captain-s-log:v1
        ports:
        - containerPort: 8080
        env:
        - name: DB_DATABASE 
          value: "captainslog"
        - name: DB_USERNAME
          value: "captainslog"
        - name: DB_PASSWORD
          value: "Pg#123"
        - name: DB_HOST
          value: postgresql

---

apiVersion: v1
kind: Service
metadata:
  name: captainslog
spec:
  selector:
    app: captainslog
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
    protocol: TCP

